[project]
name = "rest-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiofiles>=25.1.0",
    "fastapi>=0.121.2",
    "python-multipart>=0.0.20",
    "uvicorn>=0.38.0",
]
